### DISCUSSION TITLE
yml 설정을 어떻게 할 것인가?

### DISCUSSION THREAD

**Discussion by nayonsoso** [solid-connection/solid-connect-server#112] [논의]
Related to : https://github.com/solid-connection/solid-connect-server/issues/53, https://github.com/solid-connection/solid-connect-server/issues/111

## 배경
사실 yml 관련 문제는 이전부터 제기되었으나, 우선순위에서 밀렸었습니다.
그런데 제가 이번에 직접 불편함을 느끼게 되었습니다..😵‍💫
테스트 코드를 돌리면서 특정 변수를 찾지 못하는 문제가 있었고, 이를 해결하기 위해서 yml 파일을 한참이나 봐야 했습니다.
![image](https://github.com/user-attachments/assets/67cf8c22-e8d7-478a-bb61-63932c51ffa5)

## 논의 사항
응집도가 낮은 yml 설정이 우리 코드의 유지보수성을 떨어뜨린다 느껴서, **yml 파일을 어떻게 개선할것인지**에 대해서 논의를 해보면 좋겠습니다.
(yml 설정은 변경 범위가 /resource/ 하위이므로, 소스 코드와 변경의 범위가 겹치지 않습니다. 
따라서 이 논의를 하면서 다른 작업을 이어나갈 수 있습니다 👍)

**Comment by nayonsoso** [comment]
저는 yml 관리에 있어 가장 중요한 것이 '응집도' 라고 생각합니다.
그래서 환경별 분리 or 관심사별 분리 둘 중 하나로 갔으면 좋겠습니다.

1️⃣
환경별로 분리를 하면, application-prod / application-dev / application-test 이렇게 세개의 yml 만 존재하고, 
중복되는 부분이 있더라도, 한 파일 안에 다 파악하게 할 수 있습니다.

2️⃣
관심사별로 분리를 하면, application-cloud / application-db / application-variable(`@Value` 로 주입받는 것들 모음) / application
이렇게 4개의 yml 이 존재하게 됩니다.
개인적으로 애를 먹었던 부분이, 환경 별로 달라지는 부분들이었습니다. 
`university.term` 이 local 프로파일에서는 찾아지는데, test 프로파일에서는 찾아지지 않는 등..
그런데 이렇게 정리하면 환경 별로 어떻게 다른지를 한 파일에서 보기 편합니다.

두가지 방법으로 yml 을 구성해서 직접 봐보니, 개인적으로 2번 방법이 더 편리했습니다.
1번 방법은 설정 관련 내용이 추가될수록 한 파일이 너무 뚱뚱해질 것 같기도 했고요.
그래서 2번 방법으로 관리했으면 하는데, 다른 분들의 의견도 궁금합니다!

---

추가적으로, 위백님이 https://github.com/solid-connection/solid-connect-server/issues/53#issuecomment-2282653912 이 코멘트에 달아주신 내용에 대해서 생각을 해봤습니다.
위백님은 '외부에 노출해도 되는 것 / 숨겨야 할 것'을 기준으로 나누신 것 같습니다.

그런데 **외부에 노출해도 되는 것을 반드시 노출할 필요는 없으니**, 이것을 엄격하게 나누지 않아도 될 것 같습니다.

**Reply by leesewon00** [reply]
저도 처음에 동일한 어려움을 겪었어서 공감이 되네요. 좋은 의견인 것 같습니다!
두가지 방안을 제시해주셨는데 저도 2번이 더 좋다고 생각됩니다.
보통 1번으로 활용해왔어서 2번 방안이 새롭게 느껴지기는 하는데요, 중복도 줄어들고 원하는 부분을 빠르게 파악하기에 더 용이할 것 같네요.
처음 설정하는데 있어서는 조금 어려움이 있겠지만 잘 도입된다면 매우 좋은 방안인 것 같습니다.

추가적으로 2번 방안을 떠올린 계기가 조금 궁금한데요 이전에 활용해본 경험이 있으신건지, 새롭게 생각해낸 아이디어인건지 궁금합니다!

**Reply by nayonsoso** [reply]
> 추가적으로 2번 방안을 떠올린 계기가 조금 궁금한데요 이전에 활용해본 경험이 있으신건지, 새롭게 생각해낸 아이디어인건지 궁금합니다!

사실 저도 2번 방법은 처음입니다😅
그래서 처음 yml 구조 변경을 하려 할 때, 1번 방법으로 먼저 변경을 해봤습니다.
그랬더니 한 파일이 너무 길어져 오히려 읽기 어려워지더라고요...

솔리드 커넥션은 외부 서비스를 사용하는게 많아 aws, kakao, jwt, redis,
그 외에도 어플리케이션에 필요한 university.term 과 같은 변수도 yml 로 관리하고 있습니다.
이들을 분류를 하는 것이 더 가독성을 높일 수 있을 것이라 생각해서 2번 방법을 떠올리게 되었습니다.

**Reply by leesewon00** [reply]
답변 감사합니다!

추가적으로 db 경로 등 배포환경과 로컬환경에서 다르게 사용하고 있는 내용이 존재하는데,
이 부분에 대해서는 어떻게 적용할 예정이신지 궁금합니다!

**Reply by nayonsoso** [reply]
```yml

# 공통 설정
spring:
  data:
    redis:
      host: localhost
      port: 6379

--- # prod profile 에서만 활성화될 설정
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: {prod_db_url}

--- # dev profile 에서만 활성화될 설정
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: {dev_db_url}

--- # test profile 에서만 활성화될 설정
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
```

이런식으로 spring.config.activate.on-profile 를 사용할 예정입니다!
